name: Test Self-Hosted GitHub Runner with Private Registry

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test Environment
        run: |
          echo "Runner Name: $RUNNER_NAME"
          uname -a

      - name: Ensure Python is Installed
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          python3 --version

      - name: Run `test.py`
        run: python3 test/test.py

      - name: Log in to Private Registry
        run: |
          docker login registry.registry.svc.cluster.local:5000 \
            -u ${{ secrets.REGISTRY_USERNAME }} \
            -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push with Kaniko
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.registry.svc.cluster.local:5000/my-app:latest
          builder: kaniko
          cache: true

      - name: Run Tests in Kubernetes
        run: |
          kubectl run my-app-test \
            --image=registry.registry.svc.cluster.local:5000/my-app:latest \
            --restart=Never \
            --command -- sh -c "echo 'Hello from Kubernetes!' && exit 0"